steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/charged-ridge-434119-s5/my-image:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/charged-ridge-434119-s5/my-image:$COMMIT_SHA']
images:
  - 'gcr.io/charged-ridge-434119-s5/my-image:$COMMIT_SHA'
options:
  logging: NONE
serviceAccount: codebuild-test@charged-ridge-434119-s5.iam.gserviceaccount.com
